# Generated by Django 4.1.3 on 2022-12-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBlockSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_class', models.CharField(blank=True, help_text='Additional CSS class names for div.block-code (alternative to using Meta.block_class).', max_length=255)),
            ],
            options={
                'verbose_name': 'Code Blocks',
            },
        ),
    ]
